services:
  webhookrelay:
    image: webhookrelay/webhookrelay:latest
    build: .
    ports:
      - "8099:8099"
    volumes:
      - ./config/example.json:/app/config.json:ro
    command: ["-config", "/app/config.json"]
