services:
  webhookrelay:
    image: webhookrelay/webhookrelay:latest
    build: .
    ports:
      - ${HOST_PORT}:8099
    volumes:
      - ${CONFIG_DIR}:/app/config:ro
    command: ["-config", "/app/config.json"]
